### ISSUE TITLE
Switching languages is not working

### ISSUE THREAD

**Issue by bromagosa** [cycomachead/snap-app#6]
It seems language files are not being pulled with the snap submodule:

`Failed to load resource: the server responded with a status of 404 (Not Found)`

**Comment by cycomachead** [comment]
Interesting. Language files should be there since they are a part of Snap<em>!</em>.

Does loading extra files like libraries, costumes, etc work?

**Comment by bromagosa** [comment]
Nope, same problem:

`GET http://localhost:8000/Sounds/SOUNDS 404 (Not Found)`

Maybe it's got something to do with serving static files?

**Comment by cycomachead** [comment]
I think the domain of the subfolders is incorrect. I should be able to fix it tomorrow but you could probably look at overriding IDE::resourceURL if you're curious.

(Loading languages might require a tweak to snap though.)

## 

Michael Ball
From my iPhone
michaelball.co

**Comment by cycomachead** [comment]
Ok, I just pushed a fix. If you pull it, everything should load. (You'll probably need to `git submodule update` to grab the latest Snap! Updates as well.)

**Comment by bromagosa** [comment]
Great, it does work now! :)
